logging:
  config: classpath:log4j2.xml
  level:
    root: DEBUG
spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/
    username: postgres
    password: password
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: password
    locations: filesystem:src/main/resources/db/migration
  logging:
    level:
      org.flywaydb.core.internal.command: debug
  redis:
    host: localhost
    port: 6379

third-party:
  approval-client:
    url: "https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc"