spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/
    username: postgres
    password: password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: password
    locations: filesystem:src/main/resources/db/migration
  logging:
    level:
      org.flywaydb.core.internal.command: debug

third-party:
  approval-client:
    url: "https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc"